# Generated by Django 4.2 on 2023-04-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('validade', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=1, max_digits=10)),
                ('medida', models.CharField(choices=[('G', 'gramas'), ('ml', 'ml'), ('U', 'unidades')], max_length=10)),
            ],
        ),
    ]
