# Generated by Django 4.1.7 on 2023-04-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='medida',
            field=models.CharField(choices=[('g', 'gramas'), ('ml', 'ml'), ('U', 'unidades')], max_length=10),
        ),
    ]
