# Generated by Django 4.1.7 on 2023-04-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_armazenamento_produto_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='medida',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='minimo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='produto',
            name='local',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='situacao',
            field=models.CharField(choices=[('Acabando', 'Acambando'), ('Acabou', 'Acabou'), ('Cheio', 'Cheio')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
